development: &common
  allowed_origin: 'https://www.pibiapp.com'
  courier:
    enabled:  true
    from:     'noreply@pibibot.com'
  user:
    default_categories: [
      'Bills',
      'Car',
      'Cinema',
      'Clothes',
      'Electronics',
      'Food',
      'Fun',
      'Gaming',
      'Gifts',
      'Groceries',
      'Hobbies',
      'Household',
      'Luxury',
      'Medicine',
      'Music',
      'Nightlife',
      'Online',
      'Phone',
      'Salary',
      'School',
      'Shopping',
      'Travel',
      'Utility'
    ]

production:
  <<: *common
  # allowed_origin: 'http://pibi.kodoware.com'

test:
  <<: *common
  courier:
    enabled: false
  credentials:
    cookie:
      secret: 'adooken'
