development: &common
  allowed_origin: 'https://www.pibiapp.com'
  default_categories: [
    'Bills',
    'Car',
    'Cinema',
    'Clothes',
    'Electronics',
    'Food',
    'Fun',
    'Gaming',
    'Gifts',
    'Groceries',
    'Hobbies',
    'Household',
    'Luxury',
    'Medicine',
    'Music',
    'Nightlife',
    'Online',
    'Phone',
    'Salary',
    'School',
    'Shopping',
    'Travel',
    'Utility'
  ]

production:
  <<: *common

test:
  <<: *common
  upload_path: tmp/uploads
