development: &common
  user:
    default_categories: [
      'Bills',
      'Car',
      'Cinema',
      'Clothes',
      'Electronics',
      'Food',
      'Fun',
      'Gaming',
      'Gifts',
      'Groceries',
      'Hobbies',
      'Household',
      'Luxury',
      'Medicine',
      'Music',
      'Nightlife',
      'Online',
      'Phone',
      'Salary',
      'School',
      'Shopping',
      'Travel',
      'Utility'
    ]

production:
  <<: *common

test:
  <<: *common
