development: &common
  allowed_origin: ''
  courier:
    enabled:  true
    from:     'noreply@pibibot.com'
  user:
    default_categories: [
      'Food',
      'Car',
      'Utility',
      'Luxury',
      'Shopping',
      'Outing',
      'Travel',
      'Household',
      'Hobbies',
      'Clothes',
      'Gifts',
      'Electronics',
      'Music',
      'Fun',
      'Online Gaming',
      'Phone'
    ]

production:
  <<: *common
  # allowed_origin: 'http://pibi.kodoware.com'

test:
  <<: *common
  courier:
    enabled: false
  credentials:
    cookie:
      secret: 'adooken'
