development: &common
  allowed_origin: ''
  cookie_domain: '.pibi.kodoware.com'
  amqp_exchange: 'pibi.cloud'
  user:
    default_categories: [
      'Bills',
      'Car',
      'Cinema',
      'Clothes',
      'Electronics',
      'Food',
      'Fun',
      'Gaming',
      'Gifts',
      'Groceries',
      'Hobbies',
      'Household',
      'Luxury',
      'Medicine',
      'Music',
      'Nightlife',
      'Online',
      'Phone',
      'Salary',
      'School',
      'Shopping',
      'Travel',
      'Utility'
    ]

production:
  <<: *common
  cookie_domain: '.pibiapp.com'
  # allowed_origin: 'http://pibi.kodoware.com'

test:
  <<: *common
  credentials:
    cookie:
      secret: 'adooken'
