development:
  database: &common
    host: 'localhost'
    port: '3306'
    un:   'root'
    pw:   ''
    db:   'pibid'

test:
  database:
    <<: *common
    db: 'pibid_test'

production:
  database:
    <<: *common