development:
  database: &common
    host: 'localhost'
    un:   'root'
    pw:   ''
    db:   'pibid'
    secret: 'foobar'

test:
  database:
    <<: *common
    db: 'pibid_test'

production:
  database:
    <<: *common
    secret: 'change me'