development:
  database: &common
    host: 'localhost'
    un:   'pibid'
    pw:   'p1b1d'
    db:   'pibiv2'

test:
  database:
    <<: *common
    db: 'pibiv2_test'

production:
  database:
    <<: *common
