development:
  oauth: &common
    host: 'http://api.pibi.kodoware.com'
    facebook:
      key: ''
      secret: ''
    github:
      key:    ''
      secret: ''
    google:
      key: ''
      secret: ''

production:
  oauth:
    <<: *common
    host: 'https://api.pibiapp.com'
    facebook:
      key:    ''
      secret: ''
    github:
      key:    ''
      secret: ''
    google:
      key: ''
      secret: ''
