$LOAD_PATH << File.join(File.dirname(__FILE__), '..')

ENV['RACK_ENV'] = 'test'

require 'rspec'
require 'rack/test'
require 'rack/utils'
require 'app'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus => true

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.include Rack::Test::Methods
end

def mockup_user(q = {})
  User.destroy

  @some_salt = Pibi.salt
  @mockup_user_params = {
    name: 'Mysterious Mocker',
    email: 'very@mysterious.com',
    provider: 'pibi',
    password:               User.encrypt(@some_salt),
    password_confirmation:  User.encrypt(@some_salt)
  }.merge(q)
  @user = @u = User.create(@mockup_user_params)
  @account = @a = @user.accounts.first
end
