---
user: www-data
group: www-data
pid: tmp/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
address: 127.0.0.1
port: 9122
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
chdir: /srv/http/pibid
tag: pibid